### ISSUE TITLE
Package for kodi

### ISSUE THREAD

**Issue by razzeee** [xbmc/elm-chorus#53]

**Comment by Razzeee** [comment]
We now use parcel, which should be a first step

**Comment by iamsdas** [comment]
Just want to clarify, by package do you mean npm package?

**Comment by razzeee** [comment]
https://github.com/xbmc/elm-chorus/pull/81

**Comment by razzeee** [comment]
No, package to a kodi addon

Suryashankar Das ***@***.***> schrieb am Mi., 30. März 2022,
22:22:
