### ISSUE TITLE
Keep subnav static

### ISSUE THREAD

**Issue by Razzeee** [xbmc/elm-chorus#54]

**Comment by patelaryan7751** [comment]
can you provide some more info on it?

**Comment by Razzeee** [comment]
I'll take a look later, has been some time, can't remember right now.

**Comment by patelaryan7751** [comment]
> I'll take a look later, has been some time, can't remember right now.

okay!

**Comment by Razzeee** [comment]
I've got no idea anymore, what this was about. Will close for now. Sorry.
