### ISSUE TITLE
[issue] Development env issue

### ISSUE THREAD

**Issue by StarTrooper08** [xbmc/elm-chorus#63]
What issue I m facing?
- I just setup the development environment for elm-chorus but I m getting the following issue.
 Here , it is:
![kodi](https://user-images.githubusercontent.com/72031540/114673960-62637200-9d24-11eb-91e9-f3895c1516a0.PNG)

How can I resolve this?

**Comment by StarTrooper08** [comment]
The lost connection to kodi pop up is coming again and again.

**Comment by Razzeee** [comment]
But your running a Kodi instance with the ports exposed?

**Comment by StarTrooper08** [comment]
What should I do then ??

**Comment by StarTrooper08** [comment]
Any solution!

**Comment by StarTrooper08** [comment]
> But your running a Kodi instance with the ports exposed?

I new to this so I m unaware about the same . What I can do now??

**Comment by Razzeee** [comment]
Please refer to this https://kodi.wiki/view/Web_interface#Turning_on_the_web_interface

**Comment by StarTrooper08** [comment]
Ok thanks 👍
